_job: &job
  env: &job_env
    expected_result: '"-eq 0"'

_native_job: &native_job
  <<: *job
  script: |
    test/run
    eval "[ ${?} ${expected_result} ]"
  env:
    <<: *job_env

_docker_job: &docker_job
  <<: *job
  os: linux
  script: |
    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
        "${docker_img_name}:${docker_img_version}" \
        sh -c \
          "${install_cmd} ${default_pkgs} ${pkgs} && test/run"
    eval "[ ${?} ${expected_result} ]"
  _docker_job_env: &docker_job_env
    <<: *job_env
    default_pkgs: bash

_alpine_docker_job: &alpine_docker_job
  <<: *docker_job
  _alpine_docker_job_env: &alpine_docker_job_env
    <<: *docker_job_env
    docker_img_name: alpine
    docker_img_version: latest
    install_cmd: '"apk -q update && apk -q add"'
  env:
    <<: *alpine_docker_job_env

_centos_docker_job: &centos_docker_job
  <<: *docker_job
  _centos_docker_job_env: &centos_docker_job_env
    <<: *docker_job_env
    docker_img_name: centos
    docker_img_version: latest
    install_cmd: '"yum -q -y install"'
  env:
    <<: *centos_docker_job_env

_debian_docker_job: &debian_docker_job
  <<: *docker_job
  _debian_docker_job_env: &debian_docker_job_env
    <<: *docker_job_env
    docker_img_name: debian
    install_cmd: '"apt-get update && apt-get install -y"'

_ubuntu_docker_job: &ubuntu_docker_job
  <<: *debian_docker_job
  _ubuntu_docker_job_env: &ubuntu_docker_job_env
    <<: *debian_docker_job_env
    docker_img_name: ubuntu

language: shell
services:
  - docker
jobs:
  - <<: *native_job
    os: osx
  - <<: *native_job
    os: linux
  - <<: *alpine_docker_job
  - <<: *centos_docker_job
    env:
      <<: *centos_docker_job_env
      expected_result: '"-ne 0"' # failures due to missing `where`
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: oldoldstable-slim
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: oldstable-slim
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: stable-slim
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: testing-slim
  - <<: *ubuntu_docker_job
    env:
      <<: *ubuntu_docker_job_env
      docker_img_version: latest
  - <<: *ubuntu_docker_job
    env:
      <<: *ubuntu_docker_job_env
      docker_img_version: rolling
  - <<: *ubuntu_docker_job
    env:
      <<: *ubuntu_docker_job_env
      docker_img_version: devel
