_predicate:
  known_bad: "!" &known_bad

_native_job: &native_job
  script: |
    if ${predicate} test/run
    then
      true; return
    else
      false; return
    fi

_docker_job: &docker_job
  os: linux
  script: |
    if ${predicate} docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
        "${docker_img_name}:${docker_img_version}" \
        sh -c \
          "${install_cmd} ${default_pkgs} ${pkgs} && test/run"
    then
      true; return
    else
      false; return
    fi
  _docker_job_env: &docker_job_env
    default_pkgs: bash

_alpine_docker_job: &alpine_docker_job
  <<: *docker_job
  _alpine_docker_job_env: &alpine_docker_job_env
    docker_img_name: alpine
    docker_img_version: latest
    <<: *docker_job_env
    install_cmd: '"apk -q update && apk -q add"'
  env:
    <<: *alpine_docker_job_env

_centos_docker_job: &centos_docker_job
  <<: *docker_job
  _centos_docker_job_env: &centos_docker_job_env
    docker_img_name: centos
    docker_img_version: latest
    <<: *docker_job_env
    install_cmd: '"yum -q -y install"'
  env:
    <<: *centos_docker_job_env

_debian_docker_job: &debian_docker_job
  <<: *docker_job
  _debian_docker_job_env: &debian_docker_job_env
    docker_img_name: debian
    <<: *docker_job_env
    install_cmd: '"apt-get update && apt-get install -y"'

_ubuntu_docker_job: &ubuntu_docker_job
  <<: *debian_docker_job
  _ubuntu_docker_job_env: &ubuntu_docker_job_env
    docker_img_name: ubuntu
    <<: *debian_docker_job_env

language: shell
services:
  - docker
jobs:
  - <<: *native_job
    os: osx
  - <<: *native_job
    os: linux
  - <<: *alpine_docker_job
  - <<: *centos_docker_job
    env:
      predicate: *known_bad # failures due to missing `where`
      <<: *centos_docker_job_env
  - <<: *debian_docker_job
    env:
      docker_img_version: oldoldstable-slim
      <<: *debian_docker_job_env
  - <<: *debian_docker_job
    env:
      docker_img_version: oldstable-slim
      <<: *debian_docker_job_env
  - <<: *debian_docker_job
    env:
      docker_img_version: stable-slim
      <<: *debian_docker_job_env
  - <<: *debian_docker_job
    env:
      docker_img_version: testing-slim
      <<: *debian_docker_job_env
  - <<: *ubuntu_docker_job
    env:
      docker_img_version: latest
      <<: *ubuntu_docker_job_env
  - <<: *ubuntu_docker_job
    env:
      docker_img_version: rolling
      <<: *ubuntu_docker_job_env
  - <<: *ubuntu_docker_job
    env:
      docker_img_version: devel
      <<: *ubuntu_docker_job_env
