_docker_job: &docker_job
  os: linux
  script: |
    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
        "${docker_img_name}:${docker_img_version}" \
        sh -c \
          "${install_cmd} ${default_pkgs} ${pkgs} && test/run"
  _docker_job_env: &docker_job_env
    default_pkgs: bash

_alpine_docker_job: &alpine_docker_job
  <<: *docker_job
  _alpine_docker_job_env: &alpine_docker_job_env
    <<: *docker_job_env
    install_cmd: '"apk -q update && apk -q add"'
    docker_img_name: alpine
    docker_img_version: latest

_debian_docker_job: &debian_docker_job
  <<: *docker_job
  _debian_docker_job_env: &debian_docker_job_env
    install_cmd: '"apt update && apt install -y"'
    docker_img_name: debian

_native_job: &native_job
  script: test/run

language: shell
services:
  - docker
jobs:
  - os: osx
    <<: *native_job
  - os: linux
    <<: *native_job
  - <<: *alpine_docker_job
    env:
      <<: *alpine_docker_job_env
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: oldoldstable
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: oldstable
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: stable
  - <<: *debian_docker_job
    env:
      <<: *debian_docker_job_env
      docker_img_version: testing
