script: |
  if ! ${with_docker}
  then
    test/run
    return
  fi

  docker run \
    --rm \
    --tty \
    --volume "$(pwd):$(pwd):ro" \
    --workdir "$(pwd)" \
    ${docker_img} sh -c "${install_cmd} ${pkgs} && test/run"

language: shell
os:
  - linux
  - osx
env:
  - with_docker=false
  - |
    with_docker=true
    docker_img=alpine
    install_cmd='apk add'
    pkgs="bash"
  - |
    with_docker=true
    docker_img=debian:oldoldstable
    install_cmd='apt update && apt install -y'
    pkgs="bash"
services:
  - docker
