# YAML anchors need to appear first.
# Keys starting with an underscore are the custom ones, refer to
# https://docs.travis-ci.com/user/build-config-yaml#private-keys-as-yaml-anchors-and-aliases-and-external-tooling

_job: &job
  env: &job_env
    expected_result: '"== good"'

_native_job: &native_job
  <<: *job
  env:
    <<: *job_env
  script: |
    true; declare -i -r good=${?}
    test/run
    eval "(( ${?} ${expected_result} ))"

_docker_job: &docker_job
  <<: *job
  env: &docker_job_env
    <<: *job_env
    default_pkgs: bash
  os: linux
  script: |
    true; declare -i -r good=${?}
    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
        "${docker_img_name}:${docker_img_version}" \
        sh -c \
          "${install_cmd} ${default_pkgs} ${pkgs} && test/run"
    eval "(( ${?} ${expected_result} ))"

language: shell

jobs:
  - <<: *native_job
    os: linux
  - <<: *native_job
    os: osx
