script: test/run
language: shell
os:
  - linux
  - osx
services:
  - docker
before_install:
  - |
    if ! command -v docker 2> /dev/null
    then
      true; return
    fi

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      alpine sh -c 'apk add bash && test/run'

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      debian:oldoldstable sh -c 'apt update && apt install -y bash && test/run'

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      debian:oldstable sh -c 'apt update && apt install -y bash && test/run'

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      debian:stable sh -c 'apt update && apt install -y bash && test/run'

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      debian:unstable sh -c 'apt update && apt install -y bash && test/run'

    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
      debian:testing sh -c 'apt update && apt install -y bash && test/run'
