# YAML anchors need to appear first.
# Keys starting with an underscore are the custom ones, refer to
# https://docs.travis-ci.com/user/build-config-yaml#private-keys-as-yaml-anchors-and-aliases-and-external-tooling

_job: &job
  env: &job_env
    expected_result: '"== good"'

_native_job: &native_job
  <<: *job
  env:
    <<: *job_env
  script: |
    true; declare -i -r good=${?}
    test/run
    eval "(( ${?} ${expected_result} ))"

_docker_job: &docker_job
  <<: *job
  env: &docker_job_env
    <<: *job_env
    default_pkgs: bash
  os: linux
  script: |
    true; declare -i -r good=${?}
    docker run \
      --rm \
      --tty \
      --volume "$(pwd):$(pwd):ro" \
      --workdir "$(pwd)" \
        "${docker_img_name}:${docker_img_version}" \
        sh -c \
          "${install_cmd} ${default_pkgs} ${pkgs} && test/run"
    eval "(( ${?} ${expected_result} ))"

_alpine_docker_job: &alpine_docker_job
  <<: *docker_job
  env: &alpine_docker_job_env
    <<: *docker_job_env
    docker_img_name: alpine
    docker_img_version: latest
    install_cmd: '"apk -q update && apk -q add"'

_centos_docker_job: &centos_docker_job
  <<: *docker_job
  env: &centos_docker_job_env
    <<: *docker_job_env
    docker_img_name: centos
    docker_img_version: latest
    install_cmd: '"yum -q -y install"'

_debian_docker_job: &debian_docker_job
  <<: *docker_job
  _debian_docker_job_env: &debian_docker_job_env
    <<: *docker_job_env
    docker_img_name: debian
    install_cmd: '"apt-get update && apt-get install -y"'

language: shell

services:
  - docker

jobs:
  - <<: *alpine_docker_job
    env:
      <<: *alpine_docker_job_env
      expected_result: '"!= good"' # failures due to tools missing
  - <<: *native_job
    os: linux
  - <<: *centos_docker_job
    env:
      <<: *centos_docker_job_env
      expected_result: '"!= good"' # failures due to missing `where`
  - <<: *native_job
    os: osx
