" load system defaults when present
let defaults_file = "/usr/share/vim/vim"
	\ . (v:version / 100) . (v:version % 10)
	\ . "/defaults.vim"
if filereadable(defaults_file)
	execute "source " . defaults_file
endif

" mouse in vim confuses me
set mouse=

" quickly toggle paste mode
set pastetoggle=<F2>

" spell check in English (US)
" disable with `setlocal nospell`
" add words to dictionary with `zg`
setlocal spell spelllang=en_us

" use `\s` for spell suggestions drop-down
nnoremap \s ea<C-X><C-S>

" Mark tabs and trailing whitespace
set listchars=tab:‗‗,trail:‗
set list

if executable("powerline")
        " Set up powerline, see
        " https://powerline.readthedocs.io/en/latest/troubleshooting.html#my-vim-statusline-is-hidden-only-appears-in-split-windows
        set laststatus=2
endif

if filereadable("/usr/lib/ycmd/ycm_extra_conf.py")
	" Set up youcompleteme
	let g:ycm_global_ycm_extra_conf = "/usr/lib/ycmd/ycm_extra_conf.py"
	filetype on
endif
